#!/usr/bin/env python3
"""Amalgamate the HdrHistogram_c core into a self-contained drop-in.

The core (record path + value/percentile read path + iterators) lives in
``src/hdr_histogram.c`` and depends only on the C standard library and libm --
no zlib, threads, logging codec, interval recorder or phaser. This script emits
it as a couple of files that an embedding project can vendor instead of tracking
the whole source tree:

  <out>/hdr_histogram.c   the engine, with the private headers (hdr_atomic.h,
                          hdr_tests.h) inlined
  <out>/hdr_histogram.h   the public API (already self-contained; copied as-is)
  <out>/hdr_malloc.h      the default libc allocator hook (copied as-is)

Override the allocator exactly as for the normal build, by compiling with
  -DHDR_MALLOC_INCLUDE='"my_alloc.h"'

Usage:
  script/amalgamate.py --output amalgamated      # (re)generate
  script/amalgamate.py --check  amalgamated      # verify the tree is up to date
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# The core translation unit and the search path for its local includes.
ROOT_TU = "src/hdr_histogram.c"
PUBLIC_HEADER = "hdr_histogram.h"            # shipped alongside, referenced by name
INCLUDE_DIRS = ["src", "include/hdr"]
# Files copied verbatim next to the amalgamated .c.
COPY_FILES = {
    PUBLIC_HEADER: "include/hdr/hdr_histogram.h",
    "hdr_malloc.h": "src/hdr_malloc.h",
}

# Matches  #include "foo.h"  or  #include <hdr/foo.h>  (not #include SOME_MACRO).
INCLUDE_RE = re.compile(r'^\s*#\s*include\s*(?:"([^"]+)"|<([^>]+)>)\s*$')


def version():
    path = os.path.join(ROOT, "include/hdr/hdr_histogram_version.h")
    try:
        with open(path) as f:
            m = re.search(r'#define\s+HDR_HISTOGRAM_VERSION\s+"([^"]+)"', f.read())
            if m:
                return m.group(1)
    except OSError:
        pass
    return "unknown"


def resolve(name):
    """Return the repo-relative path of a local header, or None if not local."""
    base = os.path.basename(name)
    for d in INCLUDE_DIRS:
        p = os.path.join(d, base)
        if os.path.isfile(os.path.join(ROOT, p)):
            return p
    return None


def inline(path, seen, out):
    """Append `path`'s content to `out`, recursively inlining local includes."""
    with open(os.path.join(ROOT, path)) as f:
        lines = f.readlines()
    out.append("/* ---- begin %s ---- */\n" % path)
    for line in lines:
        m = INCLUDE_RE.match(line)
        if m:
            name = m.group(1) or m.group(2)
            if os.path.basename(name) == PUBLIC_HEADER:
                if PUBLIC_HEADER not in seen:
                    seen.add(PUBLIC_HEADER)
                    out.append('#include "%s"\n' % PUBLIC_HEADER)
                continue
            target = resolve(name)
            if target is not None:
                if target not in seen:
                    seen.add(target)
                    inline(target, seen, out)
                continue
        # system include, the HDR_MALLOC_INCLUDE macro hook, or plain code
        out.append(line)
    out.append("/* ---- end %s ---- */\n" % path)


def generate():
    banner = (
        "/*\n"
        " * HdrHistogram_c core -- amalgamated single-file build.\n"
        " *\n"
        " * GENERATED by script/amalgamate.py from HdrHistogram_c %s. DO NOT EDIT;\n"
        " * change the sources and regenerate. Public domain (see hdr_histogram.h).\n"
        " */\n" % version()
    )
    out = [banner]
    # Empty seen-set: the public header include in hdr_histogram.c is emitted once
    # at its natural position; later references (e.g. from hdr_tests.h) are deduped.
    inline(ROOT_TU, set(), out)
    return "".join(out)


def copies():
    result = {}
    for dst, src in COPY_FILES.items():
        with open(os.path.join(ROOT, src)) as f:
            result[dst] = f.read()
    return result


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--output", metavar="DIR", help="write the amalgamation to DIR")
    g.add_argument("--check", metavar="DIR", help="fail if DIR is not up to date")
    args = ap.parse_args()

    files = {"hdr_histogram.c": generate()}
    files.update(copies())

    out_dir = args.output or args.check
    if args.check:
        stale = []
        for name, content in files.items():
            p = os.path.join(ROOT, out_dir, name)
            try:
                with open(p) as f:
                    current = f.read()
            except OSError:
                current = None
            if current != content:
                stale.append(name)
        if stale:
            sys.stderr.write(
                "amalgamation out of date: %s\n"
                "run: script/amalgamate.py --output %s\n" % (", ".join(sorted(stale)), out_dir))
            return 1
        print("amalgamation up to date (%s)" % out_dir)
        return 0

    dst = os.path.join(ROOT, out_dir)
    os.makedirs(dst, exist_ok=True)
    for name, content in files.items():
        with open(os.path.join(dst, name), "w") as f:
            f.write(content)
    print("wrote %d files to %s" % (len(files), out_dir))
    return 0


if __name__ == "__main__":
    sys.exit(main())
