#!/usr/bin/env python3
"""Amalgamate the HdrHistogram_c core into a self-contained drop-in.

The core (record path + value/percentile read path + iterators) lives in
``src/hdr_histogram.c`` and depends only on the C standard library and libm --
no zlib, threads, logging codec, interval recorder or phaser. This script emits
it as a couple of files that an embedding project can vendor instead of tracking
the whole source tree. The output is generated, not committed: it is attached to
each GitHub release, and can be regenerated from any checkout or release tarball.

  <out>/hdr_histogram.c   the engine, with the private headers (hdr_atomic.h,
                          hdr_tests.h) inlined
  <out>/hdr_histogram.h   the public API (already self-contained; copied as-is)
  <out>/hdr_malloc.h      the default libc allocator hook (copied as-is; not written
                          with --malloc-include)

Override the allocator exactly as for the normal build, by compiling with
  -DHDR_MALLOC_INCLUDE='"my_alloc.h"'
or bake it in with --malloc-include, which makes my_alloc.h the default instead
of hdr_malloc.h. Only hdr_histogram.c and hdr_histogram.h are written: hdr_malloc.h
is not, and my_alloc.h is not created (it is yours, kept alongside the output).
A -DHDR_MALLOC_INCLUDE on the compiler command line still wins.

--output is relative to the current directory, so the script can be run from a
release tarball into your own tree.

Usage:
  script/amalgamate.py --output DIR
  script/amalgamate.py --output deps/hdr_histogram --malloc-include hdr_redis_malloc.h
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# The core translation unit and the search path for its local includes.
ROOT_TU = "src/hdr_histogram.c"
PUBLIC_HEADER = "hdr_histogram.h"            # shipped alongside, referenced by name
INCLUDE_DIRS = ["src", "include/hdr"]
# Files copied verbatim next to the amalgamated .c.
COPY_FILES = {
    PUBLIC_HEADER: "include/hdr/hdr_histogram.h",
    "hdr_malloc.h": "src/hdr_malloc.h",
}

# Matches  #include "foo.h"  or  #include <hdr/foo.h>  (not #include SOME_MACRO).
MALLOC_DEFAULT = '#define HDR_MALLOC_INCLUDE "hdr_malloc.h"'
HEADER_NAME_RE = re.compile(r'^[A-Za-z0-9_][A-Za-z0-9_./+-]*$')

# a trailing /* ... */ comment is allowed (it is dropped when the header is inlined)
INCLUDE_RE = re.compile(r'^\s*#\s*include\s*(?:"([^"]+)"|<([^>]+)>)\s*(?:/\*.*\*/\s*)?$')


def version():
    path = os.path.join(ROOT, "include/hdr/hdr_histogram_version.h")
    try:
        with open(path) as f:
            m = re.search(r'#define\s+HDR_HISTOGRAM_VERSION\s+"([^"]+)"', f.read())
            if m:
                return m.group(1)
    except OSError:
        pass
    return "unknown"


def resolve(name, angle):
    """Return the repo-relative path of a local header, or None if not local.

    Quoted includes are project-local. Angle includes are system headers unless
    they are <hdr/...>, so <foo.h> is never inlined just because src/ has a foo.h.
    """
    if angle and not name.startswith("hdr/"):
        return None
    base = os.path.basename(name)
    for d in INCLUDE_DIRS:
        p = os.path.join(d, base)
        if os.path.isfile(os.path.join(ROOT, p)):
            return p
    return None


def inline(path, seen, out):
    """Append `path`'s content to `out`, recursively inlining local includes."""
    with open(os.path.join(ROOT, path)) as f:
        lines = f.readlines()
    out.append("/* ---- begin %s ---- */\n" % path)
    for line in lines:
        m = INCLUDE_RE.match(line)
        if m:
            name = m.group(1) or m.group(2)
            angle = m.group(1) is None
            if os.path.basename(name) == PUBLIC_HEADER:
                if PUBLIC_HEADER not in seen:
                    seen.add(PUBLIC_HEADER)
                    out.append('#include "%s"\n' % PUBLIC_HEADER)
                continue
            target = resolve(name, angle)
            if target is not None:
                if target not in seen:
                    seen.add(target)
                    inline(target, seen, out)
                continue
        # system include, the HDR_MALLOC_INCLUDE macro hook, or plain code
        out.append(line)
    out.append("/* ---- end %s ---- */\n" % path)


def generate(malloc_include=None):
    banner = (
        "/*\n"
        " * HdrHistogram_c core -- amalgamated single-file build.\n"
        " *\n"
        " * GENERATED by script/amalgamate.py from HdrHistogram_c %s. DO NOT EDIT;\n"
        " * change the sources and regenerate. Public domain (see hdr_histogram.h).\n"
        " */\n" % version()
    )
    out = [banner]
    # Empty seen-set: the public header include in hdr_histogram.c is emitted once
    # at its natural position; later references (e.g. from hdr_tests.h) are deduped.
    inline(ROOT_TU, set(), out)
    body = "".join(out)
    if malloc_include:
        if body.count(MALLOC_DEFAULT) != 1:
            sys.exit("cannot find the HDR_MALLOC_INCLUDE default in %s" % ROOT_TU)
        body = body.replace(
            MALLOC_DEFAULT, '#define HDR_MALLOC_INCLUDE "%s"' % malloc_include)
    return body


def copies(malloc_include=None):
    result = {}
    for dst, src in COPY_FILES.items():
        if malloc_include and dst == "hdr_malloc.h":
            continue
        with open(os.path.join(ROOT, src)) as f:
            result[dst] = f.read()
    return result


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--output", metavar="DIR", required=True,
                    help="write the amalgamation to DIR (relative to the current directory)")
    ap.add_argument("--malloc-include", metavar="HEADER",
                    help="make HEADER the default allocator header instead of hdr_malloc.h "
                         "(you supply it; e.g. hdr_redis_malloc.h)")
    args = ap.parse_args()
    if args.malloc_include is not None and not HEADER_NAME_RE.match(args.malloc_include):
        ap.error("--malloc-include must be a plain header file name")

    files = {"hdr_histogram.c": generate(args.malloc_include)}
    files.update(copies(args.malloc_include))

    dst = os.path.abspath(args.output)
    os.makedirs(dst, exist_ok=True)
    for name, content in files.items():
        with open(os.path.join(dst, name), "w") as f:
            f.write(content)
    print("wrote %d files to %s" % (len(files), args.output))
    return 0


if __name__ == "__main__":
    sys.exit(main())
